### ISSUE TITLE
Automated Pipeline Development

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#12]
- Building:
  - Code scan: SonarQube / CodeQL
  - Write building script
  - Implement building pipeline
- Testing:
  - Write UT/FVT testing case
  - Implement testing pipeline
automation

**Comment by MarkAckert** [comment]
For some implementation details: CI/CD should be built in Github Actions and use the https://github.com/zowe-actions/shared-actions actions built by the community wherever it makes sense. For examples of the actions in use check major Zowe repos (zowe-cli, api-layer, zlux, zowe-install-packaging, etc.)

**Comment by MarkAckert** [comment]
Complete with #182
