### ISSUE TITLE
Design for Zowe Chat Future User Scenario

### ISSUE THREAD

**Issue by Phoebecdy91** [zowe/zowe-chat#121]
**User Story**
- Zowe Chat posted a “high CPU usage” alert. 
- Annette, IT Operator, noticed this alert and performed some operations to find out where the problem lies.
- Then she engaged Zach, System Programmer, to fix the problem in the job.
- Zach fix the problem and notify Annette
- Annette double check that the problem has been fixed.

**Comment by TessieWang** [comment]
[Zowe Chat user story - 01 Sep.pdf](https://github.com/zowe/zowe-chat/files/9467119/Zowe.Chat.user.story.pdf)
