### ISSUE TITLE
Zowe Chat Avatar in Chat Tools

### ISSUE THREAD

**Issue by Phoebecdy91** [zowe/zowe-chat#122]
To make Zowe Chat more highly recognizable:
- Need an avatar for Zowe Chat.
- Double confirm with @MarkAckert to see if there is any branding guidelines that we need to follow.

**Comment by Phoebecdy91** [comment]
On-going: updated by Sep 2nd - not determined yet
<img width="784" alt="image" src="https://user-images.githubusercontent.com/23204849/188051582-ba30575a-ed83-4219-9a7f-5f7cb9f5b5a8.png">

**Comment by Phoebecdy91** [comment]
Iteration of the branding image:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/23204849/188356972-283a1f88-a8cd-4d72-a5db-bf6952507f07.png">

Latest design:
- including the elements of chatting bubble, bot and branding name
- could be recognize even it is a small avatar in the interface
- can also be used in some promotion materials

avatar for different chat tools:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/23204849/188357075-a4f5e4d8-a826-44d0-b7e4-e02f0c0b0b9d.png">
Example of putting in deck:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/23204849/188357271-7d160649-2323-4962-8e35-d3d3c9a98790.png">

**Comment by Phoebecdy91** [comment]
New design assumption - Sep 14: try some more transformation based on Zowe original logo 

Questions:
- what extent of consistency we would like to keep?
- what specific font and color that we can use?
- what extra color could be used for new branding?

<img width="494" alt="图片" src="https://user-images.githubusercontent.com/23204849/190101380-6140b6cf-e0cc-40cd-a563-c8d0fd42775a.png">

**Comment by Phoebecdy91** [comment]
Need a draft guideline for open community: **still updating...**
updated by Sep 19
<img width="954" alt="image" src="https://user-images.githubusercontent.com/23204849/190965859-67b6c47d-77d8-4e72-a7e7-a5c1bebaf47d.png">

**Comment by jmertic** [comment]
What is the purpose of this guideline?

**Comment by Phoebecdy91** [comment]
@jmertic It is just the draft proposal. Haven't drill down into specific details yet. But I guess we can define the guideline from these perspectives. 
From last TSC call, we found that we haven't got this kind of guideline for Zowe branding. So I am trying to find a way that is applicable for different projects/components in the near futures.
Of course, need you and team's help for moving forward. Let's see whether it can better fit Zowe image in the community.
We can have more discussion for this.

**Comment by Phoebecdy91** [comment]
Need to keep the original Zowe Logo as the avatar in current stage, before the final decision in open community: https://github.com/zowe/community/issues/1716

**Comment by Phoebecdy91** [comment]
@XuehongBJLiang please use this one for the avatar before we branding design finished.
![Zowe Chat avartar](https://user-images.githubusercontent.com/23204849/197152328-9af95b10-1813-4687-ac5f-2ca75c029715.png)
