### ISSUE TITLE
Bug: MS Teams: Redundent asterisk characters are shown in the name field of USS file list view

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#159]
**Describe the bug**
Redundent aterisk characters are shown in the name field of USS file list view. See the screen shot please.

**Steps to Reproduce**

1. Launch your MS Teams client
2. Run zos file list status <your home directory> 
3. Check the result

**Expected behavior**
The name field is shown in bold without any redundant asterisk characters

**Screenshots**
<img width="593" alt="image" src="https://user-images.githubusercontent.com/105369904/198677538-5df4aa17-f652-425e-a1fb-a4ed9d480a98.png">

**Logs**
If applicable, add server logs collected at the time of your problem.

**Details**
 - Version and build number: [e.g. 0.4.4-SNAPSHOT build # 155]
 - Chat service: [e.g. Slack, Mattermost]
 - NodeJS and NPM versions

**Additional context**

**Comment by XuehongBJLiang** [comment]
<img width="668" alt="图片" src="https://user-images.githubusercontent.com/105443843/198860911-6d28a0b2-ed38-4e99-bc5e-7097fb7af717.png">
