### ISSUE TITLE
Bug: MS Teams: The title of USS file detail view is shown in italic when path include asterisk character

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#162]
**Describe the bug**
The title of USS file detail view is shown in italic when path include asterisk character

**Steps to Reproduce**

1. Login MS Teams client
2. Execute zos file command to show USS file details

**Expected behavior**
The title is shown correctly

**Screenshots**
<img width="962" alt="image" src="https://user-images.githubusercontent.com/105369904/198684288-2edcde8e-cdf5-414b-a231-33d21deabbb9.png">

**Logs**
If applicable, add server logs collected at the time of your problem.

**Details**
 - Version and build number: [e.g. 0.4.4-SNAPSHOT build # 155]
 - Chat service: [e.g. Slack, Mattermost]
 - NodeJS and NPM versions

**Additional context**

**Comment by XuehongBJLiang** [comment]
<img width="646" alt="图片" src="https://user-images.githubusercontent.com/105443843/198860889-11aff462-ad9d-4abe-b592-70839c1cc668.png">
