### ISSUE TITLE
Bug: Empty error message is returned for the command `zos file list mounts <your mount point>`

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#163]
**Describe the bug**
Empty error message is returned for the command `zos file list mounts <your mount point>`

**Steps to Reproduce**

1. Launch your chat tool
2. Executed the command `zos file list mounts <your mount point>`
3. Check the bot reply and `chatServer.log`

**Expected behavior**
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/105369904/198685792-e294d3d3-1922-4d54-b1a1-7e10d763355e.png">

**Screenshots**

**Logs**
If applicable, add server logs collected at the time of your problem.

**Details**
 - Version and build number: [e.g. 0.4.4-SNAPSHOT build # 155]
 - Chat service: [e.g. Slack, Mattermost]
 - NodeJS and NPM versions

**Additional context**

**Comment by XuehongBJLiang** [comment]
<img width="1016" alt="图片" src="https://user-images.githubusercontent.com/105443843/198860849-c59390f8-dbaf-4703-b34a-19e734abe02e.png">
