### ISSUE TITLE
End-User Documentation 

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#17]

**Comment by MarkAckert** [comment]
End-user documentation should focus on how to users interact with the Zowe ChatBot from their Chat Client of choice. This should include at least: 

- authenticating with the zowe chatbot
- basic commands available in zowe chat
- requesting help from the zowe chatbot
- interacting with chatbot via contextual actions
- common error codes / scenarios and remediations
- other FAQ section?
