### ISSUE TITLE
Scan initial code contribution to see this repository. 

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-chat#2]
The source code at [https://github.com/Joe-Winchester/zowe-chat-staging](https://github.com/Joe-Winchester/zowe-chat-staging) should be ready for scanning by the LF tools, ready for moving across into this repository.

**Comment by Joe-Winchester** [comment]
@MarkAckert.  The repository https://github.com/Joe-Winchester/zowe-chat-staging should now be public.   Let me know if you have any problems accessing it and hopefully you should be able to begin the scan ready for moving the code across into this repository to book up the project.

**Comment by MarkAckert** [comment]
Update - expecting this to complete by 5/31.

**Comment by MarkAckert** [comment]
Updated ETA, 6/3.

**Comment by MarkAckert** [comment]
This is done, closing
