### ISSUE TITLE
Investigate designer's mockup for job scenario 

### ISSUE THREAD

**Issue by TingXieIBM** [zowe/zowe-chat#20]
Investigate designer's mockup for job scenario to evaluate and determine how to enhance common bot framework

**Comment by Phoebecdy91** [comment]
@HollyXieIBM please check the design mockup and let me know the feasibility from you and team's perspective. See this issue: #24

**Comment by Phoebecdy91** [comment]
### Job Management sub-scenario 1 
**View status of a specific job:** zowe zos-jobs view job-status-by-jobid j123

Sub-scenario | Complexity Evaluation | Feasibility
--|--|--
1. Show Job detailed info | 1 |_Need input from Dev_  
2. Job log related | 3 | Need further investigation
3. Filter/Create a job through input value for attributes | 2 | need investigation on pop-up

1. Show Job detailed info:
- [ ] Cannot redirect to 3270, Zowe CLI, but able to redirect to Zowe Explorer for opening a job
- [ ] One more step to drill down for log related details: for MVP release. 
- [ ] Clarify icons for different job status and make sure it is applicable for different chatting tools
<img width="584" alt="image" src="https://user-images.githubusercontent.com/23204849/169974817-f13a7a8d-7ce8-4fe5-8a93-fa5dbd10629f.png">

2. Job log related:
- [ ] remove "View Details" for error code in MVP.
- [ ] need to investigate how to show log related info: feasibility and what could be shown as the brief info.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/23204849/169974891-8ebc4734-7b02-49df-9f6f-494f5ded655e.png">

3. Filter/Create a job through input value for attributes:
- [ ] need to investigate the feasibility and limitation of pop-up dialog
- [ ] UX: simplify fields number
<img width="443" alt="image" src="https://user-images.githubusercontent.com/23204849/169976037-a45221e6-e07e-42c9-9e7d-a4a97e3ad35b.png">

**Comment by Phoebecdy91** [comment]
Design updated: [Job Management - Iteration 2 - 0525.pdf](https://github.com/zowe/zowe-chat/files/8771099/Job.Management.-.Iteration.2.-.0525.pdf)


Things need further discussion from Dev team:
- Is it the key status that users care about jobs: 🚫 Abended, ❌ JCL Error, 🔵 Active, ✅ Finished, ⏳ Input
- Does it make sense to have "Resubmit a job" in Zowe Chat?
- How to parse info in different Log?
- What might be the key parameters that users used most for navigating to a specific job?

**Comment by Phoebecdy91** [comment]
@XuehongBJLiang Here is the updated design for user flow, including Slack and Teams:
[Zowe Chat - user flow .pdf](https://github.com/zowe/zowe-chat/files/8861166/Zowe.Chat.-.user.flow.pdf)

The design elements and views for different chatting tools are slightly different, so here is the example for different tools: [Zowe Chat - design for 3 tools .pdf](https://github.com/zowe/zowe-chat/files/8861176/Zowe.Chat.-.design.for.3.tools.pdf)
