### ISSUE TITLE
Design Mockup - Job Management

### ISSUE THREAD

**Issue by Phoebecdy91** [zowe/zowe-chat#24]
### **Job Management Scenario**

- **View status of a specific job:**  e.g. `zowe zos-jobs view job-status-by-jobid j123`
Job detailed info, related jobs (with similar name)

- **List jobs of specific user or the name with prefix:** e.g.  `zowe zos-jobs list jobs -o "ibmu*" -p "myjo*" `
Job status summary, job name list with status, job details (next step)

- **List jobs, displaying only the job ID of each job with table format:** e.g. `zowe zos-jobs list jobs --rff jobid --rft table`
Job status summary, table

- **List jobs with execution data:**  e.g. `zowe zos-jobs list jobs —exec-data`
Job status summary, job name list with status, execution data, job details (next step)

- **List jobs with specific status:** e.g. active, abended job, CC, JCL error, input (don’t have related CLI cmd so far)
Job status summary, job name list with status, job details (next step)

- **Create a new connection or View the Job by filtering**
Hint for how to filter jobs: Name related, Connection related, File Path, Content related, Response Format

**Comment by Phoebecdy91** [comment]
@Joe-Winchester @CarsonCook @Wusong-Fang @HollyXieIBM @XuehongBJLiang 

Please check the design updates as attached. 
[Zowe Chat Design - Job Management - Iteration 2.pdf](https://github.com/zowe/zowe-chat/files/8728235/Zowe.Chat.Design.-.Job.Management.-.Iteration.2.pdf)

A couple of questions need further confirmation with you all:
1. Create/Search jobs via chat
- I found that create a new job or search a job in CLI, Zowe explorer is cumbersome. User can only enter attributes in one input box. And there might be multiple clicks but user never know how many fields left to be filled in. Especially for the people who doesn't have mainframe knowledge (could be the use case of Barclays). 
- So I am wondering **if possible for us to allow user create/search jobs by entering attributes. See Slide 12-13.** The attributes were categorized based on the CLI cmd.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/23204849/169273595-851c3ba2-ec94-48df-b0b5-108764e20d94.png">

2. For listing data in the table format: e.g. `zowe zos-jobs list jobs --rff jobid --rft table`
- what will user do to the table?
- can user download table and select different file type?

Feel free to leave your comments here. Anything related to the feature design, wording, new thoughts, feasibility.
I will schedule meeting if needed to have further discussion.

**Comment by Joe-Winchester** [comment]
Hi @Phoebecdy91 ,  you're right that for the Zowe Explorer v1 it is cumbersome for users to only be able to drive one input box.  This is because the Zowe Explorer has to be able to run in Theia/Eclipse Che which limits the type of editors that the squad can use.   For Zowe v2 this has improved with team configuration files where details are entered in an editor.
For the `--rft table` typically what a user might do in a DevOps pipeline is query particular fields and then make a decision based on that (for example starting a job that's inactive).

**Comment by Phoebecdy91** [comment]
Design updated: [Job Management - Iteration 2 - 0525.pdf](https://github.com/zowe/zowe-chat/files/8771157/Job.Management.-.Iteration.2.-.0525.pdf)

**Comment by Phoebecdy91** [comment]
Design iteration 4:
[Job Management - Iteration 4 - 3 chatting tools.pdf](https://github.com/zowe/zowe-chat/files/8963742/Job.Management.-.Iteration.4.-.3.chatting.tools.pdf)

**Comment by Phoebecdy91** [comment]
Design iteration 5: there are key pages include here. Could see the basic design component and need content suggestion/
[iteration 5.zip](https://github.com/zowe/zowe-chat/files/8974263/iteration.5.zip)
@TingXieIBM @XuehongBJLiang

**Comment by Phoebecdy91** [comment]
Design completed. Will refine it if we got extra feedback from users.

**Comment by Phoebecdy91** [comment]
All the design interfaces images:
[Zowe Chat-Mattermost.zip](https://github.com/zowe/zowe-chat/files/9099765/Zowe.Chat-Mattermost.zip)
[Zowe Chat-Mattermost.zip](https://github.com/zowe/zowe-chat/files/9099765/Zowe.Chat-Mattermost.zip)
[Zowe Chat-mobile.zip](https://github.com/zowe/zowe-chat/files/9099776/Zowe.Chat-mobile.zip)
[Zowe Chat-mobile.zip](https://github.com/zowe/zowe-chat/files/9099776/Zowe.Chat-mobile.zip)
[Zowe Chat-Slack.zip](https://github.com/zowe/zowe-chat/files/9099778/Zowe.Chat-Slack.zip)
[Zowe Chat-Slack.zip](https://github.com/zowe/zowe-chat/files/9099778/Zowe.Chat-Slack.zip)
[Zowe Chat-Teams.zip](https://github.com/zowe/zowe-chat/files/9099781/Zowe.Chat-Teams.zip)
[Zowe Chat-Teams.zip](https://github.com/zowe/zowe-chat/files/9099781/Zowe.Chat-Teams.zip)
