### ISSUE TITLE
Draft contribution guidelines

### ISSUE THREAD

**Issue by TingXieIBM** [zowe/zowe-chat#35]

**Comment by CarsonCook** [comment]
APIML contributing as an example: https://github.com/zowe/api-layer/blob/v2.x.x/CONTRIBUTING.md

- how to contact the squad
- Break down of modules (ideally this is a list of links to their own readmes)
- Misc working guidelines
- branch, PR and commit conventions
- code styling guidelines
- expectations for testing
- documentation (comments, readmes, docs site, etc) guidelines
- breakdown of issues (what sizes mean, how we plan issues, labels to pay attention to, etc)

**Comment by TingXieIBM** [comment]
Understanding Modules - Wusong

**Comment by TingXieIBM** [comment]
https://github.com/zowe/zowe-chat/blob/prior-main/assets/Contribution%20Guidelines.md

**Comment by TingXieIBM** [comment]
Branch tags:
<team-tag> chat
<work-tag> Github issue number

**Comment by TingXieIBM** [comment]
File naming:
node js,  need one package name - follow the naming rule from zowe cli.

**Comment by TingXieIBM** [comment]
Code Guidelines:  typescript configuration

**Comment by TingXieIBM** [comment]
Testing and building : follow the rules from Zowe CLI

**Comment by TingXieIBM** [comment]
PR review process?
2 reviewers at least
Pull requests should remain open for at least 24 hours, or until close of business next business day (accounting for weekends and holidays).
Anyone can comment on a pull request to request delay on merging or to get questions answered.

**Comment by TingXieIBM** [comment]
Zowe CLI guildeline link: 
https://github.com/Zowe/zowe-cli/blob/master/CONTRIBUTING.md#file-naming-guidelines

**Comment by MacNale** [comment]
If contributing.md is not the appropriate place for the following sections then please ignore -

Versioning for common bot framework
Breaking changes in SDK
Integration testing with dummy bot
Do we need to maintain CHANGELOG
Where and how to store the Architecture diagrams/UX stuff
