### ISSUE TITLE
Create Image and content for zowe.org site

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-chat#4]
@Phoebecdy91 to create the image that will be mashup of the slack JOBS scenario together with graphics for Slack/Teams/Mattersmost (to show the support for those three offerings).    For inspiration see the python-sdk on zowe.org (that has three graphics) and other offerings that have functional graphics against them.

**Comment by Phoebecdy91** [comment]
![Chat thumbnail for web - V1](https://user-images.githubusercontent.com/23204849/167978138-a8cf5795-027e-4e63-b2ee-4509d50c7da6.png)
@Joe-Winchester @MarkAckert  here is the thumbnail~ I am thinking maybe we can emphasize some key features here: from overview to details, show detailed error code msg.
Feel free to let me know if there is any suggestions, like image might mislead users or over commit something. I am happy to iterate it. THX!

**Comment by Joe-Winchester** [comment]
The site https://www.zowe.org/ is live with the graphic and the incubator project called out at the top of the site !

**Comment by Phoebecdy91** [comment]
@Joe-Winchester @MarkAckert  I just updated the thumbnail, being more consistent with our MVP version. Could you help me updated in the zowe.org website?
![Chat thumbnail for web - V2](https://user-images.githubusercontent.com/23204849/197554328-799c2f6d-5c21-4bb8-8103-5bcac9ab3151.png)
