### ISSUE TITLE
Install and Configuration Documentation

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-chat#70]

**Comment by nannanli** [comment]
Document how to install and configure Zowe Chat. This will include the following topics: 

- System requirements (hardware, software)
- Installing (how to download the install package and install, methods of installing, how to start/stop) 
- Configuring (any configurations that are needed to run Zowe Chat on Z) 

Estimate: 3PW (2PW for writing, 1PW for testing)

**Comment by nannanli** [comment]
Configuration topics converted from Z ChatOps are stored here in the Zowe docs repo: https://github.com/zowe/docs-site/tree/zowe-chat-docs/docs/user-guide/zowe-chat
