### ISSUE TITLE
Research - Event Driven Notifications

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-chat#79]
The initial technical preview for Zowe ChatBot is composed of request/response style actions, i.e., users input jobs list / jobs submit, dataset read / dataset list, and expect a response from the ChatBot. 

However, there are additional use cases for Zowe ChatBot built on push events. More generally, we should research how ChatBot may receive event notifications from external sources, and how extenders can leverage this functionality. Should extenders be able to surface their own listeners for external events?

**Comment by TingXieIBM** [comment]
The contributing process from IBM has been approved for the common data model and its REST APIs.
